const data = [
  {
    gameId: "1",
    gameName: "Viking",
    gameThumbnailUrl: "https://i.ibb.co/rFYPn09/Viking-slot-2-1-01.png",
    gameHostLink: "https://slot-vikings.vercel.app/",
    type: "featured",
    category: "fish",
  },
  {
    gameId: "2",
    gameName: "Mafia",
    gameThumbnailUrl: "https://i.ibb.co/0MgKxs0/Walking-Death-4-01-01.png",
    gameHostLink: "https://slot-mafia.vercel.app",
    type: "featured",
    category: "slot",
  },
  {
    gameName: "GCT",
    gameId: "3",
    gameThumbnailUrl: "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
    gameHostLink: "https://slot-golden-china-town.vercel.app",
    type: "hot",
    category: "fish",
  },
  {
    gameName: "GCT",
    gameId: "3",
    gameThumbnailUrl: "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
    gameHostLink: "https://slot-golden-china-town.vercel.app",
    type: "hot",
    category: "fish",
  },
  {
    gameName: "GCT",
    gameId: "3",
    gameThumbnailUrl: "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
    gameHostLink: "https://slot-golden-china-town.vercel.app",
    type: "hot",
    category: "fish",
  },
  {
    gameName: "GCT",
    gameId: "3",
    gameThumbnailUrl: "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
    gameHostLink: "https://slot-golden-china-town.vercel.app",
    type: "hot",
    category: "fish",
  },
  {
    gameName: "GCT",
    gameId: "3",
    gameThumbnailUrl: "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
    gameHostLink: "https://slot-golden-china-town.vercel.app",
    type: "hot",
    category: "fish",
  },
  {
    gameName: "GCT",
    gameId: "3",
    gameThumbnailUrl: "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
    gameHostLink: "https://slot-golden-china-town.vercel.app",
    type: "hot",
    category: "fish",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "4",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "new",
    category: "fish",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "5",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "new",
    category: "fish",
  },

  {
    gameName: "GoldOfEgypt",
    gameId: "8",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "new",
    category: "fish",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "9",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "new",
    category: "slot",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "10",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "new",
    category: "slot",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "11",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "",
    category: "fish",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "12",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "",
    category: "fish",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "13",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "",
    category: "fish",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "14",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "",
    category: "slot",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "15",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "",
    category: "fish",
  },
  {
    gameName: "Game 1",
    gameId: "16",
    gameThumbnailUrl: "https://i.ibb.co/TRqcHG7/game1-thumbnail.jpg",
    gameHostLink: "https://goldenchinatown.netlify.app",
    type: "featured",
    category: "slot",
  },
  {
    gameName: "Game 2",
    gameId: "17",
    gameThumbnailUrl: "https://i.ibb.co/MCckg5M/game2-thumbnail.jpg",
    gameHostLink: "https://exmpcheck.netlify.app",
    type: "",
  },
  {
    gameName: "Game",
    gameId: "30",
    gameThumbnailUrl: "https://i.ibb.co/MCckg5M/game2-thumbnail.jpg",
    gameHostLink: "https://exmpcheck.netlify.app",
    type: "",
    category: "slot",
  },
  {
    gameName: "GoldOfEgypt",
    gameId: "18",
    gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
    gameHostLink: "https://slot-gold-of-egypt.vercel.app",
    type: "",
  },
  //   {
  //     slotGame: [
  //       {
  //         gameId: "1",
  //         gameName: "Viking",
  //         gameThumbnailUrl: "https://i.ibb.co/rFYPn09/Viking-slot-2-1-01.png",
  //         gameHostLink: "https://slot-vikings.vercel.app/",
  //         type: "",
  //       },
  //       {
  //         gameId: "2",
  //         gameName: "Mafia",
  //         gameThumbnailUrl: "https://i.ibb.co/0MgKxs0/Walking-Death-4-01-01.png",
  //         gameHostLink: "https://slot-mafia.vercel.app",
  //         type: "",
  //       },
  //       {
  //         gameName: "GCT",
  //         gameId: "3",
  //         gameThumbnailUrl:
  //           "https://i.ibb.co/7gK8YsN/Egyptian-Treasures-1-01.png",
  //         gameHostLink: "https://slot-golden-china-town.vercel.app",
  //         type: "hot",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "4",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "5",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "6",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "7",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "8",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "9",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "10",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "new",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "11",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "12",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "13",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "14",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "",
  //       },
  //       {
  //         gameName: "GoldOfEgypt",
  //         gameId: "15",
  //         gameThumbnailUrl: "https://i.ibb.co/Sn2prcb/Gold-Of-Egypt-1-01.png",
  //         gameHostLink: "https://slot-gold-of-egypt.vercel.app",
  //         type: "",
  //       },
  //     ],

  //     kenoGame: [
  //       {
  //         gameName: "Game 1",
  //         gameId: "1",
  //         gameThumbnailUrl: "https://i.ibb.co/TRqcHG7/game1-thumbnail.jpg",
  //         gameHostLink: "https://goldenchinatown.netlify.app",
  //         type: "",
  //       },
  //       {
  //         gameName: "Game 2",
  //         gameId: "2",
  //         gameThumbnailUrl: "https://i.ibb.co/MCckg5M/game2-thumbnail.jpg",
  //         gameHostLink: "https://exmpcheck.netlify.app",
  //         type: "",
  //       },
  //     ],
  //   },
];

export default data;
